name: Deploy
run-name: ${{ github.actor }} is deploying Hugo Site from GH push 🚀
on:
  push:
    branches:
      - master
      
  workflow_dispatch:
  
defaults:
  run:
    shell: bash
    
jobs:
  deploy:
    permissions:
     contents: 'write'
     id-token: 'write'
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.124.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'mycloudresume'
          workload_identity_provider: 'projects/1040086142155/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: 'gh-actions-service-account@mycloudresume.iam.gserviceaccount.com'
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --gc --minify; hugo deploy --invalidateCDN
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Post-Deployment Commit

          
